### ISSUE TITLE
Modifing data, date change

### ISSUE THREAD

**Issue by gicaz** [biolab-unige/xtens-app#10]
When i modify or create any type of data, date keeps changing.
Example:
Date inserted:                         1975-05-11
Date displayed by postgres:   1975-05-11
Date returned by node's pg:   1975-05-10T23:00:00.000Z

**Comment by Zigur** [comment]
Not sure about what you mean by this

When you convert the ISO string 1975-05-11 to a JavaScript date it becomes 1975-05-11T00:00:00CET which is exactly 1975-05-10T23:00:00.000Z (zulu time is equivalent to GMT or UTC, while CET is GMT+1). So the date itself is correct, it should not be represented "as its is"
