### ISSUE TITLE
Password Update on Users

### ISSUE THREAD

**Issue by Zigur** [biolab-unige/xtens-app#14]
I would suggest to implement this a HTTP PATCH method

PATCH /operator/password (or PATCH /password?)

{
    "oldPasswoed" ..,
   "newPassword": ...,
   "confirmedNewPassword: ...
}

Verify oldPassword and test equality between newPassword and confirmedNewPassword.

**Comment by gicaz** [comment]
Added feature, commit:
https://github.com/biolab-unige/xtens-app/commit/c18c44c795caf7b61cffd58d978be775eba919cd
