### ISSUE TITLE
Secure the XTENS routes

### ISSUE THREAD

**Issue by Zigur** [biolab-unige/xtens-app#19]
Write explicitly the allowed routes in XTENS

**Comment by gicaz** [comment]
TODO:
- close blueprints actions and then connect routes to every existing method (models edit methods).
- Comment unused methods ( buildHierarchy dataType, migrate - migrateCGH - populatedb   Main) 
- Close blueprints shortcuts
- Then ensure all tests continue to pass

**Comment by gicaz** [comment]
- Reorder Controller's methods

**Comment by gicaz** [comment]
Merged branch ManageHooks: handled filecontent Ulpoad and Download routes
