### ISSUE TITLE
Projects management

### ISSUE THREAD

**Issue by gicaz** [biolab-unige/xtens-app#26]
Handle projects through Groups ( many to many association).
Use the existing datatype privileges system to filter a group to a specific set of datatypes (related to a specific project).
Operators view only the filtered datatype structure.

**Comment by Zigur** [comment]
To do it compliant to ISA or other data repositories:

Add 1-to-many project -> dataType
Add many-to-many project -> group
There would be a ring project-group-dataType

Move privileges from group-dataType to group-project

An option would be denormalize the "Data" type adding an "idProject" field. But is not recommended

**Comment by Zigur** [comment]
1) Add server-side constraint to dataType parent-child relationship
2) Add list of available projects as a session variable
3) Put the project list in the menu bar (only for users). Switching from a project to the other refresh the data (also for the advanced search)
4) After login add intermediate model to select a project
