### ISSUE TITLE
Data Types don't show up in web application

### ISSUE THREAD

**Issue by LizzAlice** [biolab-unige/xtens-app#35]
The Data types are saved correctly and do also show up in the PostgreSQL database, but they don't show up in the web application and it is not possible to select them and create a graph.

**Comment by Zigur** [comment]
@LizzAlice By default no permissions levels or privileges are set for the DataTypes.
User groups (a.k.a. "groups") have a privilege level to the various data types: this can be VIEW_OVERVIEW (limited view), VIEW_DETAILS (can view all metadata), DOWNLOAD (meaning that group can download bulk data), EDIT (all the previous + can edit or create new data. At least a group need this).

To set the privileges on the Menu bar go to: Management > Groups.
Here you can also create new groups or add/remove users from groups. For each group you can access the privileges levels clicking the link "DataType" . From that page you can set/edit the permission.

Users can be added from Management > Operators and then added to groups on the group page.
We support Projects at an embryonal stage through API only, they will be introduced at the interface level with the next release, late April/early May 

Once you have fixed that you can create new Subjects and/or Data from Data Management > Subject and Data Management > Data. If the data type has "file Upload" enabled you can drag and drop files in the dropzone.

I will make a tutorial and upload it to the wiki soon

Hope this helps, let me know
