### ISSUE TITLE
Not update Subject Attributes Sex and Code  

### ISSUE THREAD

**Issue by gicaz** [biolab-unige/xtens-app#9]
No error response.
Update of all other attributes works properly.

**Comment by Zigur** [comment]
This should have been fixed with the last commit on xtens-pg:
https://github.com/biolab-unige/xtens-pg/commit/6a082321818a3ea03cd3a7e4ce395faea16dbdd3

Let me know how it goes now.

**Comment by gicaz** [comment]
Now it Works properly
